DROP TABLE IF EXISTS `recettes`;

CREATE TABLE `recettes` (
 `id` int NOT NULL AUTO_INCREMENT,
 `titre` VARCHAR(100),
 `categorie`VARCHAR(10),
 `ingredient0` VARCHAR(100),
 `ingredient1` VARCHAR(100),
 `ingredient2` VARCHAR(100),
 `ingredient3` VARCHAR(100),
 `ingredient4` VARCHAR(100),
 `ingredient5` VARCHAR(100),
 `ingredient6` VARCHAR(100),
 `ingredient7` VARCHAR(100),
 `ingredient8` VARCHAR(100),
 `ingredient9` VARCHAR(100),
 `ingredient10` VARCHAR(100),
 `ingredient11` VARCHAR(100),
 `ingredient12` VARCHAR(100),
 `ingredient13` VARCHAR(100),
 `ingredient14` VARCHAR(100),
 `etape0` VARCHAR(400),
 `etape1` VARCHAR(400),
 `etape2` VARCHAR(400),
 `etape3` VARCHAR(400),
 `etape4` VARCHAR(400),
 `etape5` VARCHAR(400),
 `etape6` VARCHAR(400),
 `etape7` VARCHAR(400),
 `etape8` VARCHAR(400),
 `etape9` VARCHAR(400),
 `etape10` VARCHAR(400),
 `etape11` VARCHAR(400),
 `etape12` VARCHAR(400),
 `etape13` VARCHAR(400),
 `etape14` VARCHAR(400),
 `imagerecette` VARCHAR(300),
 PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

INSERT INTO cuisine.recettes (titre,categorie,ingredient0,ingredient1,ingredient2,ingredient3,ingredient4,ingredient5,ingredient6,ingredient7,ingredient8,ingredient9,ingredient10,ingredient11,ingredient12,ingredient13,ingredient14,etape0,etape1,etape2,etape3,etape4,etape5,etape6,etape7,etape8,etape9,etape10,etape11,etape12,etape13,etape14,imagerecette) VALUES
	 ('Lasagnes à la bolognaise','Plat','1 paquet de pâtes à lasagne','3 oignons jaunes','2 gousses d''ail','1 branche de céleri','1 carotte','800g de pure de tomate','15cl d''eau','20cl de vin rouge','125g de parmesan','100g de farine','125g de beurre','1l de lait','600g de boeuf haché',NULL,NULL,'Faire revenir gousses hachées d''ail et les oignons émincés dans un peu d''huile d''olive.','Ajouter la carotte et la branche de céleri hachée puis la viande et faire revenir le tout.','Au bout de quelques minutes, ajouter le vin rouge. Laisser cuire jusqu''à évaporation.','Ajouter la purée de tomates, l''eau et les herbes. Saler, poivrer, puis laisser mijoter à feu doux 45 minutes.','Préparer la béchamel : faire fondre 100 g de beurre.','Hors du feu, ajouter la farine d''un coup.','Remettre sur le feu et remuer avec un fouet jusqu''à l''obtention d''un mélange bien lisse.','Ajouter le lait peu à peu. Remuer sans cesse, jusqu''à ce que le mélange s''épaississe.','Ensuite, parfumer avec la muscade, saler, poivrer. Laisser cuire environ 5 minutes, à feu très doux, en remuant. Réserver.','Préchauffer le four à 200°C (thermostat 6-7). Huiler le plat à lasagnes. Poser une fine couche de béchamel puis des feuilles de lasagnes, de la bolognaise, de la béchamel et du parmesan. Répéter l''opération 3 fois de suite.','Sur la dernière couche de lasagnes, ne mettre que de la béchamel et recouvrir de fromage râpé. Parsemer quelques noisettes de beurre.','Enfourner pour environ 25 minutes de cuisson.','Déguster',NULL,NULL,'https://images.radio-canada.ca/q_auto,w_800/v1/alimentation/recette/1x1/lasagne.jpg'),
	 ('Filet de saumon et légumes au pesto','Plat','600 g de pommes de terre nouvelles','200 g de haricots verts fins','200 g de brocolis tendres','4 filets de saumon de 120 g, écaillés et désossés','Huile d''olive','25 g de pignons de pin','½ gousse d''ail','50 g de basilic frais','15 g de parmesan','2 citrons',NULL,NULL,NULL,NULL,NULL,'Pour le pesto, épluchez l''ail et ajoutez-en la moitié dans un pichet avec les pignons de pin. Piquer les feuilles de basilic et broyer jusqu''à ce qu''elles soient finement hachées.','Ajoutez 2 à 3 cuillères à soupe d''huile d''olive extra vierge - il vous en faut juste assez pour lui donner une consistance gluante - puis râpez finement et remuez le parmesan. Donnez au mélange un dernier blitz, puis coupez le citron en deux et ajoutez un filet de jus au goût, puis assaisonnez avec une pincée de poivre noir.','Frotter les pommes de terre, puis couper les haricots et le brocoli. Cuire les pommes de terre dans une grande casserole d''eau bouillante salée pendant 15 minutes ou jusqu''à ce qu''elles soient tendres, en ajoutant les haricots et le brocoli pendant les 5 dernières minutes.','Pendant ce temps, faites chauffer une grande poêle antiadhésive à feu vif. Frotter les filets de saumon avec de l''huile d''olive et assaisonner de sel et de poivre. Placer dans la poêle chaude, côté peau vers le bas, baisser le feu à moyen et cuire pendant 4 minutes, ou jusqu''à ce que la peau soit dorée et croustillante.','Retourner les filets, puis cuire encore 2 à 3 minutes, ou jusqu''à ce qu''ils soient juste cuits. Retirez la casserole du feu, laissez reposer 30 secondes, puis ajoutez un bon filet de jus de citron et secouez la casserole.','Bien égoutter les légumes, puis les verser dans un grand bol. Ajouter le pesto, puis mélanger pour enrober.','Répartir le saumon et les légumes dans les assiettes, arroser du jus de cuisson, puis couper le citron restant en quartiers pour le presser.','Déguster',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://img.jamieoliver.com/jamieoliver/recipe-database/5p9W_lsfaXkAqPVhKib0AR.jpg?tr=w-800,h-800'),
	 ('Salade de pastèque, radis et feta','Entree','2 cuillères à soupe de pignons de pin','400 g de pastèque','200 g de radis, idéalement avec des feuilles','4 brins de menthe fraîche','50 g de fromage feta',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Faites griller les pignons de pin dans une poêle sèche antiadhésive à feu moyen pendant 1 minute ou jusqu''à ce qu''ils soient légèrement dorés, en remuant régulièrement, puis retirez-les.','Coupez l''écorce de la pastèque, retirez les graines, puis coupez-la aussi finement que possible.','Trancher très finement les radis, en gardant les belles feuilles attachées, puis assaisonner délicatement les deux avec 1 cuillère à soupe d''huile d''olive extra vierge et 2 cuillères à soupe de vinaigre de vin rouge. Goûtez et assaisonnez à la perfection avec du sel marin et du poivre noir.','Disposez la pastèque et les radis dans vos assiettes ou un plat à partager, parsemez de pignons de pin, puis détachez les feuilles de menthe.','Disposez la pastèque et les radis dans vos assiettes ou un plat à partager, parsemez de pignons de pin, puis détachez les feuilles de menthe.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://img.jamieoliver.com/jamieoliver/recipe-database/89080981.jpg?tr=w-800,h-800'),
	 ('Houmous','Entree','700 g de pois chiches','½ gousse d''ail','Cumin en poudre','Huile d''olive extra vierge','2 Cuillères à soupe de tahini','1 Citron',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Versez 1 pot de 700 g de pois chiches (jus et tout) dans un mixeur.','Épluchez et ajoutez ½ gousse d''ail, ainsi qu''une bonne pincée de sel marin, de poivre noir et de cumin moulu.','Arroser de 4 cuillères à soupe d''huile d''olive extra vierge et 2 cuillères à soupe de tahini.','Râper finement le zeste d''un demi-zeste de citron et presser tout le jus, puis fouetter jusqu''à ce qu''il soit super lisse et soyeux.','Goûtez et rectifiez l''assaisonnement si nécessaire, puis retransvasez dans le bocal d''origine pour le conserver au réfrigérateur. Pour servir, j''aime faire un puits au milieu, l''embrasser avec un peu d''huile d''olive extra vierge et une pincée de cumin moulu.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://img.jamieoliver.com/jamieoliver/recipe-database/134449925.jpg?tr=w-800,h-800'),
	 ('Tarte aux amandes, yaourt et fraise','Dessert','350 g d''amandes entières blanchies','250 g de beurre non salé','300 g de sucre semoule','3 gros oeufs fermiers','6 cuillères à soupe de confiture de fraises de qualité','1 poignée d''amandes effilées émondées','500 g de crème fraîche ou de yaourt nature',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Dans un premier temps, préparez et refroidissez la pâte, puis déposez là dans un moule à tarte à fond amovible de 28 cm. Placer au congélateur pendant 1 heure.','Préchauffez le four à 180°C, puis sortez le fond de tarte du congélateur et faites cuire pendant 15 minutes, ou jusqu''à ce qu''il soit légèrement doré. Retirer du four et laisser refroidir légèrement.','Baisser le four à 170°C','Pour faire la frangipane, mixez les amandes entières dans un robot culinaire jusqu''à obtenir une poudre fine et mettez-la dans un bol. Battre le beurre et le sucre ensemble jusqu''à consistance légère et crémeuse, puis ajouter aux amandes.','Battez légèrement les œufs et ajoutez-les au mélange. Incorporer jusqu''à ce qu''il soit complètement mélangé et lisse, puis placer au réfrigérateur pour raffermir légèrement.','Répartir la confiture sur le fond de tarte. Verser dessus le mélange de frangipane refroidi et parsemer de quelques amandes effilées.','Cuire la tarte au four pendant 40 minutes, ou jusqu''à ce que le mélange d''amandes soit devenu ferme et doré à l''extérieur mais qu''il soit encore moelleux au milieu.','Laisser refroidir environ 30 minutes, puis servir avec de la crème fraîche ou du yaourt.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://img.jamieoliver.com/jamieoliver/recipe-database/89011741.jpg?tr=w-800,h-800'),
	 ('Tarte au chocolat','Dessert','300 ml de crème fraîche','2 cuillères à soupe rases de sucre semoule','400 g de chocolat noir de qualité, (70%)','90 g de beurre doux, à température ambiante','100 ml de lait','1 fond de tarte , cuit à blanc','Poudre de cacao de qualité, pour saupoudrer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mettre la crème fraîche, le sucre et une petite pincée de fleur de sel dans une casserole et porter à ébullition.','Casser le chocolat.','Dès que le mélange bout, retirer du feu et ajouter le beurre et le chocolat. Remuer jusqu''à ce qu''il soit complètement fondu. Laisser refroidir légèrement le mélange en remuant avec le lait froid jusqu''à ce qu''il soit lisse et brillant.','Parfois, ce mélange semble s''être séparé. Laisser refroidir un peu plus et fouetter un peu de lait extra froid jusqu''à consistance lisse.','Grattez tout le mélange dans le fond de tarte cuit et refroidi à l'' aide d''une spatule.','Secouez la tarte pour l''homogénéiser et laissez refroidir environ 1 à 2 heures jusqu''à ce qu''elle soit à température ambiante. Saupoudrer de cacao en poudre.','En fin de compte, la pâte doit être courte et croustillante et la garniture doit être lisse et se couper comme du beurre.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://img.jamieoliver.com/jamieoliver/recipe-database/105860262.jpg?tr=w-800,h-800'),
	 ('Ragoût de légumes épicés','Plat','1 patate douce, (300g)','1 aubergine , (250g)','2 poivrons multicolores','2 oignons','Huile d''olive','½ botte de coriandre fraîche, (15g)','30 g de tomates séchées au soleil','2 cuillères à soupe de pâte de curry thaï','½ boîte de 400 g de lait de coco','160 g de mange-tout','2 cuillères à café de sauce soja ou de poisson','1 citron vert','2 pains plats',NULL,NULL,'Frotter 1 patate douce (300 g) et la couper en rondelles d''environ ½ cm d''épaisseur. Taillez 1 aubergine (250 g) et 2 poivrons multicolores, puis coupez-les en morceaux de 3 cm.','Faites griller les légumes dans une grande casserole sèche à feu vif pendant 5 minutes – travaillez par lots, en les déposant dans une assiette au fur et à mesure.','Pelez et émincez finement 2 oignons, puis placez-les dans la grande cocotte à feu moyen avec un filet d''huile d''olive et faites cuire 10 minutes en remuant régulièrement.','Hachez finement les tiges d''un demi-bouquet de coriandre fraîche (15 g), en réservant les feuilles pour plus tard, ainsi que 30 g de tomates séchées, puis ajoutez-les à la poêle.','Incorporer 2 cuillères à soupe de pâte de curry thaï (choisissez votre préféré) et cuire encore 3 minutes, puis verser ½ boîte de 400 g de lait de coco léger et 400 ml d''eau bouillante, et bien mélanger.','Remettez les légumes grillés dans la casserole, mettez le couvercle, réduisez le feu à doux et faites cuire doucement pendant 10 minutes, en jetant les mange-tout pendant les 2 dernières minutes.','Assaisonnez avec 2 cuillères à café de sauce soja ou de poisson, puis hachez finement et parsemez les feuilles de coriandre.','Coupez 1 citron vert en quartiers pour presser dessus, puis servez, avec des pains plats sur le côté, si vous le souhaitez.','Déguster',NULL,NULL,NULL,NULL,NULL,NULL,'https://img.jamieoliver.com/jamieoliver/recipe-database/134622143.jpg?tr=w-800,h-800'),
	 ('Pâtes au pesto de roquette et pistache','Plat','80 g de roquette','1/2 gousse d''ail','50 g de pistaches décortiquées non salées','Huile d''olive','25 g de parmesan , plus un supplément pour servir','1 citron','320 g d''asperges','300 g de linguines séchées',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Piquer 70 g de roquette sauvage dans un pilon et un mortier, puis réduire en pâte avec une pincée de sel marin.','Éplucher et écraser ½ gousse d''ail, puis piler 50 g de pistaches non décortiquées jusqu''à ce qu''elles soient fines. Pilonnez dans 4 cuillères à soupe d''huile d''olive, râpez finement 25 g de parmesan, puis pressez le jus d''1 citron. Assaisonner à la perfection avec du sel et du poivre noir, puis goûter et ajuster le pesto à votre goût.','Cuire 300 g de linguines séchées dans une casserole d''eau bouillante selon les instructions du paquet, puis égoutter en réservant une tasse d''eau de cuisson féculente.','Pendant ce temps, coupez les bouts ligneux de 320 g d''asperges.
Mélanger les pâtes avec le pesto, puis à l''aide d''un éplucheur rapide, peler les longueurs d''asperges dans la poêle, en les détachant avec un peu d''eau de cuisson réservée, si nécessaire.','Arrosez d''1 cuillère à soupe d''huile d''olive, et terminez avec les 10 g de roquette restants et un fin râpé de parmesan. Délicieux servi avec une salade croquante.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://img.jamieoliver.com/jamieoliver/recipe-database/134763338.jpg?tr=w-800,h-800'),
	 ('Soupe de panais épicée','Entree',NULL,'2 gousses d''ail','1 morceau de 5 cm de gingembre frais','Huile d''olive','1 noix de beurre','1 cuillère à soupe de garam masala','6 panais','500 ml de lait demi-écrémé','750 ml de bouillon de légumes','1 piment rouge frais',NULL,NULL,NULL,NULL,NULL,'Épluchez l''oignon, l''ail et le gingembre et hachez-les grossièrement.','Faire chauffer un filet d''huile d''olive et le beurre dans une grande casserole. Ajouter l''oignon, l''ail, le gingembre et le garam masala. Faire frire doucement pendant 10 minutes ou jusqu''à ce que les oignons soient tendres et sucrés.','Pendant ce temps, épluchez les panais et coupez-les en morceaux de 3 cm. Les incorporer au mélange d''oignons jusqu''à ce qu''ils soient bien enrobés.','Verser le lait et le bouillon, bien assaisonner et porter à ébullition. Baisser le feu et laisser mijoter 30 minutes avec un couvercle.','Au bout d''une demi-heure, vérifiez que les panais sont cuits en enfonçant un couteau. Si vous êtes satisfait, retirez-les du feu et mixez-les avec un mixeur plongeant jusqu''à ce qu''ils soient lisses et crémeux. Goûtez et rectifiez l''assaisonnement au besoin.','Épépinez et hachez finement le piment et répartissez-le sur la soupe, si vous le souhaitez. Délicieux servi avec du pain croûté et un filet supplémentaire d''huile d''olive extra vierge.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/530_1_1441789489.jpg?tr=w-800,h-800'),
	 ('Crostini - tomates et olives','Entree','20 tomates cerises','1 poignée d''olives noires ou vertes','2-3 tasses d''huile d''olive extra vierge','1 cuillère à soupe de vinaigre balsamique','Sel','Poivre','Un peu de piment séché, émietté','Pain grillé','Jeunes feuilles de basilic',NULL,NULL,NULL,NULL,NULL,NULL,'Procurez-vous une vingtaine de tomates cerises mûres, de couleurs différentes si possible, et coupez-les en quartiers. Retirez les noyaux d''une poignée d''olives noires ou vertes de bonne qualité et hachez-les.','Mélanger dans un bol avec les tomates, 2 ou 3 verres d''huile d''olive extra vierge et une gorgée de vinaigre balsamique, et assaisonner soigneusement avec du sel et du poivre et un peu de piment séché émietté.','Versez sur chacun de vos crostinis chauds et saupoudrez de petites feuilles de basilic sur le dessus.','Bon appétit !',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://img.jamieoliver.com/jamieoliver/recipe-database/oldImages/large/172_1_1438936151.jpg?tr=w-800,h-800');



