DROP TABLE IF EXISTS `recettes`;

CREATE TABLE `recettes` (
 `id` int NOT NULL AUTO_INCREMENT,
 `titre` VARCHAR(100),
 `categorie`VARCHAR(10),
 `ingredient0` VARCHAR(100),
 `ingredient1` VARCHAR(100),
 `ingredient2` VARCHAR(100),
 `ingredient3` VARCHAR(100),
 `ingredient4` VARCHAR(100),
 `ingredient5` VARCHAR(100),
 `ingredient6` VARCHAR(100),
 `ingredient7` VARCHAR(100),
 `ingredient8` VARCHAR(100),
 `ingredient9` VARCHAR(100),
 `ingredient10` VARCHAR(100),
 `ingredient11` VARCHAR(100),
 `ingredient12` VARCHAR(100),
 `ingredient13` VARCHAR(100),
 `ingredient14` VARCHAR(100),
 `etape0` VARCHAR(400),
 `etape1` VARCHAR(400),
 `etape2` VARCHAR(400),
 `etape3` VARCHAR(400),
 `etape4` VARCHAR(400),
 `etape5` VARCHAR(400),
 `etape6` VARCHAR(400),
 `etape7` VARCHAR(400),
 `etape8` VARCHAR(400),
 `etape9` VARCHAR(400),
 `etape10` VARCHAR(400),
 `etape11` VARCHAR(400),
 `etape12` VARCHAR(400),
 `etape13` VARCHAR(400),
 `etape14` VARCHAR(400),
 `imagerecette` VARCHAR(300),
 PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

INSERT INTO `recettes` (titre,
    categorie,
    ingredient0,
    ingredient1,
    ingredient2,
    ingredient3,
    ingredient4,
    ingredient5,
    ingredient6,
    ingredient7,
    ingredient8,
    ingredient9,
    ingredient10,
    ingredient11,
    ingredient12,
    ingredient13,
    ingredient14,
    etape0,
    etape1,
    etape2,
    etape3,
    etape4,
    etape5,
    etape6,
    etape7,
    etape8,
    etape9,
    etape10,
    etape11,
    etape12,
    etape13,
    etape14,
    imagerecette) VALUES
	 ('Lasagnes à la bolognaise','Plat','1 paquet de pâtes à lasagne','3 oignons jaunes','2 gousses d''ail','1 branche de céleri','1 carotte','800g de pure de tomate','15cl d''eau','20cl de vin rouge','125g de parmesan','100g de farine','125g de beurre','1l de lait','600g de boeuf haché',NULL,NULL,'Faire revenir gousses hachées d''ail et les oignons émincés dans un peu d''huile d''olive.','Ajouter la carotte et la branche de céleri hachée puis la viande et faire revenir le tout.','Au bout de quelques minutes, ajouter le vin rouge. Laisser cuire jusqu''à évaporation.','Ajouter la purée de tomates, l''eau et les herbes. Saler, poivrer, puis laisser mijoter à feu doux 45 minutes.','Préparer la béchamel : faire fondre 100 g de beurre.','Hors du feu, ajouter la farine d''un coup.','Remettre sur le feu et remuer avec un fouet jusqu''à l''obtention d''un mélange bien lisse.','Ajouter le lait peu à peu. Remuer sans cesse, jusqu''à ce que le mélange s''épaississe.','Ensuite, parfumer avec la muscade, saler, poivrer. Laisser cuire environ 5 minutes, à feu très doux, en remuant. Réserver.','Préchauffer le four à 200°C (thermostat 6-7). Huiler le plat à lasagnes. Poser une fine couche de béchamel puis des feuilles de lasagnes, de la bolognaise, de la béchamel et du parmesan. Répéter l''opération 3 fois de suite.','Sur la dernière couche de lasagnes, ne mettre que de la béchamel et recouvrir de fromage râpé. Parsemer quelques noisettes de beurre.','Enfourner pour environ 25 minutes de cuisson.','Déguster',NULL,NULL,'https://images.radio-canada.ca/q_auto,w_800/v1/alimentation/recette/1x1/lasagne.jpg'),
	 ('Filet de saumon et légumes au pesto','Plat','600 g de pommes de terre nouvelles','200 g de haricots verts fins','200 g de brocolis tendres','4 filets de saumon de 120 g, écaillés et désossés','Huile d''olive','25 g de pignons de pin','½ gousse d''ail','50 g de basilic frais','15 g de parmesan','2 citrons',NULL,NULL,NULL,NULL,NULL,'Pour le pesto, épluchez l''ail et ajoutez-en la moitié dans un pichet avec les pignons de pin. Piquer les feuilles de basilic et broyer jusqu''à ce qu''elles soient finement hachées.','Ajoutez 2 à 3 cuillères à soupe d''huile d''olive extra vierge - il vous en faut juste assez pour lui donner une consistance gluante - puis râpez finement et remuez le parmesan. Donnez au mélange un dernier blitz, puis coupez le citron en deux et ajoutez un filet de jus au goût, puis assaisonnez avec une pincée de poivre noir.','Frotter les pommes de terre, puis couper les haricots et le brocoli. Cuire les pommes de terre dans une grande casserole d''eau bouillante salée pendant 15 minutes ou jusqu''à ce qu''elles soient tendres, en ajoutant les haricots et le brocoli pendant les 5 dernières minutes.','Pendant ce temps, faites chauffer une grande poêle antiadhésive à feu vif. Frotter les filets de saumon avec de l''huile d''olive et assaisonner de sel et de poivre. Placer dans la poêle chaude, côté peau vers le bas, baisser le feu à moyen et cuire pendant 4 minutes, ou jusqu''à ce que la peau soit dorée et croustillante.','Retourner les filets, puis cuire encore 2 à 3 minutes, ou jusqu''à ce qu''ils soient juste cuits. Retirez la casserole du feu, laissez reposer 30 secondes, puis ajoutez un bon filet de jus de citron et secouez la casserole.','Bien égoutter les légumes, puis les verser dans un grand bol. Ajouter le pesto, puis mélanger pour enrober.','Répartir le saumon et les légumes dans les assiettes, arroser du jus de cuisson, puis couper le citron restant en quartiers pour le presser.','Déguster',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://img.jamieoliver.com/jamieoliver/recipe-database/5p9W_lsfaXkAqPVhKib0AR.jpg?tr=w-800,h-800'),
	 ('Salade de pastèque, radis et feta','Entree','2 cuillères à soupe de pignons de pin','400 g de pastèque','200 g de radis, idéalement avec des feuilles','4 brins de menthe fraîche','50 g de fromage feta',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Faites griller les pignons de pin dans une poêle sèche antiadhésive à feu moyen pendant 1 minute ou jusqu''à ce qu''ils soient légèrement dorés, en remuant régulièrement, puis retirez-les.','Coupez l''écorce de la pastèque, retirez les graines, puis coupez-la aussi finement que possible.','Trancher très finement les radis, en gardant les belles feuilles attachées, puis assaisonner délicatement les deux avec 1 cuillère à soupe d''huile d''olive extra vierge et 2 cuillères à soupe de vinaigre de vin rouge. Goûtez et assaisonnez à la perfection avec du sel marin et du poivre noir.','Disposez la pastèque et les radis dans vos assiettes ou un plat à partager, parsemez de pignons de pin, puis détachez les feuilles de menthe.','Disposez la pastèque et les radis dans vos assiettes ou un plat à partager, parsemez de pignons de pin, puis détachez les feuilles de menthe.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://img.jamieoliver.com/jamieoliver/recipe-database/89080981.jpg?tr=w-800,h-800'),
	 ('Houmous','Entree','700 g de pois chiches','½ gousse d''ail','Cumin en poudre','Huile d''olive extra vierge','2 Cuillères à soupe de tahini','1 Citron',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Versez 1 pot de 700 g de pois chiches (jus et tout) dans un mixeur.','Épluchez et ajoutez ½ gousse d''ail, ainsi qu''une bonne pincée de sel marin, de poivre noir et de cumin moulu.','Arroser de 4 cuillères à soupe d''huile d''olive extra vierge et 2 cuillères à soupe de tahini.','Râper finement le zeste d''un demi-zeste de citron et presser tout le jus, puis fouetter jusqu''à ce qu''il soit super lisse et soyeux.','Goûtez et rectifiez l''assaisonnement si nécessaire, puis retransvasez dans le bocal d''origine pour le conserver au réfrigérateur. Pour servir, j''aime faire un puits au milieu, l''embrasser avec un peu d''huile d''olive extra vierge et une pincée de cumin moulu.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://img.jamieoliver.com/jamieoliver/recipe-database/134449925.jpg?tr=w-800,h-800'),
	 ('Tarte aux amandes, yaourt et fraise','Dessert','350 g d''amandes entières blanchies','250 g de beurre non salé','300 g de sucre semoule','3 gros oeufs fermiers','6 cuillères à soupe de confiture de fraises de qualité','1 poignée d''amandes effilées émondées','500 g de crème fraîche ou de yaourt nature',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Dans un premier temps, préparez et refroidissez la pâte, puis déposez là dans un moule à tarte à fond amovible de 28 cm. Placer au congélateur pendant 1 heure.','Préchauffez le four à 180°C, puis sortez le fond de tarte du congélateur et faites cuire pendant 15 minutes, ou jusqu''à ce qu''il soit légèrement doré. Retirer du four et laisser refroidir légèrement.','Baisser le four à 170°C','Pour faire la frangipane, mixez les amandes entières dans un robot culinaire jusqu''à obtenir une poudre fine et mettez-la dans un bol. Battre le beurre et le sucre ensemble jusqu''à consistance légère et crémeuse, puis ajouter aux amandes.','Battez légèrement les œufs et ajoutez-les au mélange. Incorporer jusqu''à ce qu''il soit complètement mélangé et lisse, puis placer au réfrigérateur pour raffermir légèrement.','Répartir la confiture sur le fond de tarte. Verser dessus le mélange de frangipane refroidi et parsemer de quelques amandes effilées.','Cuire la tarte au four pendant 40 minutes, ou jusqu''à ce que le mélange d''amandes soit devenu ferme et doré à l''extérieur mais qu''il soit encore moelleux au milieu.','Laisser refroidir environ 30 minutes, puis servir avec de la crème fraîche ou du yaourt.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://img.jamieoliver.com/jamieoliver/recipe-database/89011741.jpg?tr=w-800,h-800'),
	 ('Tarte au chocolat','Dessert','300 ml de crème fraîche','2 cuillères à soupe rases de sucre semoule','400 g de chocolat noir de qualité, (70%)','90 g de beurre doux, à température ambiante','100 ml de lait','1 fond de tarte , cuit à blanc','Poudre de cacao de qualité, pour saupoudrer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Mettre la crème fraîche, le sucre et une petite pincée de fleur de sel dans une casserole et porter à ébullition.','Casser le chocolat.','Dès que le mélange bout, retirer du feu et ajouter le beurre et le chocolat. Remuer jusqu''à ce qu''il soit complètement fondu. Laisser refroidir légèrement le mélange en remuant avec le lait froid jusqu''à ce qu''il soit lisse et brillant.','Parfois, ce mélange semble s''être séparé. Laisser refroidir un peu plus et fouetter un peu de lait extra froid jusqu''à consistance lisse.','Grattez tout le mélange dans le fond de tarte cuit et refroidi à l'' aide d''une spatule.','Secouez la tarte pour l''homogénéiser et laissez refroidir environ 1 à 2 heures jusqu''à ce qu''elle soit à température ambiante. Saupoudrer de cacao en poudre.','En fin de compte, la pâte doit être courte et croustillante et la garniture doit être lisse et se couper comme du beurre.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'https://img.jamieoliver.com/jamieoliver/recipe-database/105860262.jpg?tr=w-800,h-800');



